### ISSUE TITLE
Linked User not work

### ISSUE THREAD

**Issue by zknafein** [StarDustCFW/StarDust-Toolkit#1] opened 2020-09-06 16:33 UTC
I have only one account, not linked with any nintendo account. Never connected to a WIFI (always on aireplane).

LinkUsers Force does not work. Just ask for reboot, and after reboot nothing changes.

Linkar Kuhaku user neither work.

Atmosphere 0.14.1
FW: 10.1.0

Try without applet-mode and with it. No EmuMMC, SD-CARD with ex-fat.

**Comment by Kronos2308** [comment] 2020-09-17 02:40
after 10 > only kuhaku is wokin but delete all save games so you have to dump your saves first

**Comment by Kronos2308** [comment] 2020-09-17 04:26
i see the problem is fixed in 
[9.8](https://github.com/StarDustCFW/StarDust-Toolkit/releases/tag/9.8)


> 
> 
> I have only one account, not linked with any nintendo account. Never connected to a WIFI (always on aireplane).
> 
> LinkUsers Force does not work. Just ask for reboot, and after reboot nothing changes.
> 
> Linkar Kuhaku user neither work.
> 
> Atmosphere 0.14.1
> FW: 10.1.0
> 
> Try without applet-mode and with it. No EmuMMC, SD-CARD with ex-fat.

**Closed as completed by Kronos2308** 2020-09-17 04:26 UTC
